---
title: "Exploring patterns of basic needs in college students"
output: html_document
---


Food insecurity among college students is problem that can impact student performance in the classroom and ultimately effect student success. The [Center for Healthy Communities](https://www.csuchico.edu/chc/) (CHC) developed the **Basic Needs Student Success Survey (BNS3)** and administered it to undergraduate students at [California State University, Chico](https://www.csuchico.edu/) in April 2019. The [Educational Opportunity Program](https://www.csuchico.edu/eop/) (EOP) office assisted in the recruitment and provided computers for students to take the survey. Participants were given a $25 gift card for their participation. Initially, EOP students were identified as the target population for this survey because of their low-income and first-generation status which makes these students more likely eligible to qualify for CalFresh.

The purpose of this cross-sectional pilot study was to create a tool that identifies student perception of the impact of receiving [CalFresh](https://www.csuchico.edu/calfresh/index.shtml) assistance on their health, nutrition, cooking confidence, time management and academic performance. 

This report provides a top level descriptive analysis of each question in the survey. Researchers and campus staff are encouraged to review the information in this analysis to formulate further research hypotheses and questions.
  


---

### How to use this site

Each tab represents specific questions from the BNS3. The questions are then grouped by topic area and labeled with a header.

Questions marked with a `r emo::ji('star')` are questions of interest for the CSU, Chico EOP office.

---

### Contact

Questions about the survey or data analysis presented in this report can be directed to:

* ##### [Stephanie Bianco](https://www.csuchico.edu/chc/about/staff/stephanie-bianco.shtml), CHC Director, PI Email: sbianco@csuchico.edu  

* ##### [Robin Donatello](https://norcalbiostat.netlify.app/), Data Manager Email: rdonatello@csuchico.edu


---

### Acknowledgements

This website was built and is maintained by Brandon Leff, Undergraduate student in Statistics and Data Science, CSU Chico, Department of Mathematics and Statistics and Kathleen Johnson, MS, Center for Healthy Communities. 